Inicio de HomePage
ricardoMogas/pfi-management-frontend pull request #9
Opened 2024-03-20 04:47 UTC by GaelChan03

![image](https://github.com/ricardoMogas/pfi-management-frontend/assets/158241242/97c3e4b7-7759-4b37-badd-f41ee8696a94)

Subí los últimos cambios, no se te olvide darle a Submit jajaja.

2024-03-23 19:42 UTC, ricardoMogas requested changes
Usar bootstrap en tu componente, Card y Grid.

2024-03-23 19:42 UTC, ricardoMogas commented on src/pages/HomePage.jsx
> +      </div>
Primero, no es necesario poner cabecera dado que ya esta en el index.html del proyecto, el navbar no es necesario, cierto que hay un **button de configuración** en donde pusiste la imagen **TuercaSF.png** , ese deberia ir en el componente navbar , y este muestra un modal, aun no se define bien para que se usara, probablemente sera para ciertas configuraciones de la app. No es necesario poner la tuerca por ahora.

2024-03-23 19:42 UTC, ricardoMogas commented on src/pages/HomePage.jsx
> +        </div>
Estos dos divs vendrian siendo dos columnas que deberan estar dentro de un card: 

- Recomiendo usar GRID de bootstrap: [https://getbootstrap.com/docs/5.3/layout/grid/](url).
- Para el card usa el componente card que te proporciona bootstrap igual: [https://getbootstrap.com/docs/5.3/components/card/](url)

Por ahora los estilos en linea que usaste estan bien, pero dado que usaremos Boostrap es necesario que lo usen en los componentes que creen para mantener consistencia en la interfaz, el css solo se usara para detalles que no queden del todo bien con bootstrap y recomiendo no sobrescribir el mismo, generara problemas con el responsive que que ya trae integrado el framework.

2024-03-24 00:22 UTC, GaelChan03 commented
Modifique el codigo para que este con Bootsrap y lo acomode de otra manera. A su vez elimine la tuerca que no era necesaria.

![image](https://github.com/ricardoMogas/pfi-management-frontend/assets/158241242/b5e793c4-f5d4-4b6d-a485-5190e0c3b2b6)

2024-04-16 00:21 UTC, ricardoMogas approved these changes

2024-04-16 00:22 UTC, merged